builds:
- main: ./cmd/hellofromgo/
  id: "cli"
  binary: cli
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    rlcp: true
    files:
      - README.md
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256