version: '3'
services:
  myapp:
    image: karamad/hellofromgo:latest
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - "80:8080"
      - "443:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
    depends_on:
      - myapp