version: '3'
services:
  myapp:
    image: karamad/hellofromgo:latest
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/cert.pem:/etc/nginx/cert.pem
      - /home/ubuntu/key.pem:/etc/nginx/key.pem
    depends_on:
      - myapp