name: Release

on:
  push:
    # run only against tags in format v1.2.3
    # tags:
    #   - 'v*'
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      # - name: Import GPG key
      #   id: gpg
      #   uses: crazy-max/ghaction-import-gpg@v5
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # - name: List GPG keys
      #   run: gpg -K
      - name: Generate go.sum file
        run: go mod tidy
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}